licornes_bundle:
    path: /
    controller: Sheeptizent\LicornesBundle\Controller\HomeController::index
    methods: GET

licornes_bundle_test:
    path: /test
    controller: Sheeptizent\LicornesBundle\Controller\TestController::index
    methods: GET